package com.roid.crash;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.view.View;

import com.roid.R;
import com.roid.ui.ActivityManager;
import com.roid.ui.dialog.ActionDialog;
import com.roid.ui.dialog.ActionDialog.DialogBtnClickListener;
import com.roid.ui.dialog.ActionDialog.DialogDismissedListener;
import com.roid.ui.dialog.ActionResultDialog;

public class CrashReportActivity extends FragmentActivity {
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		
		/* Push Activity into stack */
		ActivityManager.getInstance().pushActivity(CrashReportActivity.this);
		
		final ActionResultDialog dialog = ActionResultDialog.newInstance(this, false,
				getString(R.string.crash_report_title),
				getString(R.string.crash_report_content));
		dialog.setPositiveBtnText(getString(R.string.btn_confirm), true);
		dialog.setNegativeBtnText(null, false);
		dialog.setBtnClickListener(new DialogBtnClickListener() {
			ActionResultDialog mDialog = dialog;

			@Override
			public void onDialogBtnClick(View btn, int btnID) {
				mDialog.dismiss();
				CrashReportActivity.this.finish();
			}
		});
		dialog.setOnDismissedListener(new DialogDismissedListener() {
			@Override
			public void onDismissed(ActionDialog dialog) {
				/* Dump the logcat to file */
				LogcatDump.instance().dump("<-------- Dump by User -------->\n");
			}
		});
		/* Don't check the activity before popup dialog */
		dialog.show(getSupportFragmentManager(), "CrashReport");
		
		/* Dump the logcat to file */
		LogcatDump.instance().dump("<-------- Generated by Crash Report -------->\n");
	}
	
	public static void start(Context appContext)
	{
		Intent intent = new Intent();
		intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
		intent.setClass(appContext, CrashReportActivity.class);
		appContext.startActivity(intent);
	}

	@Override
	public void finish() {
		super.finish();
		
		/* Pop Activity off stack */
		ActivityManager.getInstance().popActivity(CrashReportActivity.this); 
	}

}
